/**
 * Platform OS — Permission Templates
 *
 * Pre-built permission sets for each role.
 * Maps Brand OS roles → ERP V3 permission system.
 *
 * WO-P2: Permission Unification
 */

import { PERMISSIONS, type PermissionCode } from "./permissions.config";

export interface PermissionTemplate {
  code: string;
  name: string;
  description: string;
  permissions: PermissionCode[];
}

// ═══════════════════════════════════════════
// Platform Templates
// ═══════════════════════════════════════════

export const TEMPLATES: Record<string, PermissionTemplate> = {
  // ── Full access ──
  platform_admin: {
    code: "platform_admin",
    name: "Platform 管理员",
    description: "拥有系统全部权限 — ERP + Brand + CRM + Platform",
    permissions: [
      // ERP — all
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.PRODUCT_VIEW, PERMISSIONS.PRODUCT_EDIT, PERMISSIONS.PRODUCT_DELETE,
      PERMISSIONS.SKU_VIEW, PERMISSIONS.SKU_EDIT, PERMISSIONS.SKU_DELETE,
      PERMISSIONS.WORK_VIEW, PERMISSIONS.WORK_EDIT, PERMISSIONS.WORK_DELETE,
      PERMISSIONS.MATERIAL_VIEW, PERMISSIONS.MATERIAL_EDIT, PERMISSIONS.MATERIAL_DELETE,
      PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_EDIT,
      PERMISSIONS.BOM_VIEW, PERMISSIONS.BOM_EDIT,
      PERMISSIONS.COST_VIEW, PERMISSIONS.COST_EDIT, PERMISSIONS.PROFIT_VIEW,
      PERMISSIONS.PRODUCTION_VIEW, PERMISSIONS.PRODUCTION_CREATE, PERMISSIONS.PRODUCTION_EDIT,
      PERMISSIONS.ORDER_VIEW, PERMISSIONS.ORDER_EDIT,
      PERMISSIONS.CUSTOMER_VIEW, PERMISSIONS.CUSTOMER_EDIT,
      PERMISSIONS.USER_VIEW, PERMISSIONS.USER_EDIT,
      PERMISSIONS.SETTING_VIEW, PERMISSIONS.SETTING_EDIT,
      PERMISSIONS.IMPORT_DATA, PERMISSIONS.EXPORT_DATA,
      PERMISSIONS.MEDIA_VIEW, PERMISSIONS.MEDIA_UPLOAD, PERMISSIONS.MEDIA_DELETE, PERMISSIONS.MEDIA_EDIT,
      PERMISSIONS.BANNER_VIEW, PERMISSIONS.BANNER_MANAGE,
      PERMISSIONS.SUPER_ADMIN,
      // Brand — all
      PERMISSIONS.BRAND_ACCESS,
      PERMISSIONS.BRAND_SERIES_VIEW, PERMISSIONS.BRAND_SERIES_EDIT,
      PERMISSIONS.BRAND_PRODUCT_VIEW, PERMISSIONS.BRAND_PRODUCT_EDIT,
      PERMISSIONS.BRAND_ARTICLE_VIEW, PERMISSIONS.BRAND_ARTICLE_CREATE, PERMISSIONS.BRAND_ARTICLE_EDIT,
      PERMISSIONS.BRAND_ARTICLE_DELETE, PERMISSIONS.BRAND_ARTICLE_PUBLISH,
      PERMISSIONS.BRAND_PAGE_VIEW, PERMISSIONS.BRAND_PAGE_EDIT,
      PERMISSIONS.BRAND_SEO_VIEW, PERMISSIONS.BRAND_SEO_EDIT,
      PERMISSIONS.BRAND_TAG_VIEW, PERMISSIONS.BRAND_TAG_EDIT,
      PERMISSIONS.BRAND_MATERIAL_VIEW, PERMISSIONS.BRAND_MATERIAL_EDIT,
      PERMISSIONS.BRAND_MEDIA_UPLOAD,
      // CRM — all
      PERMISSIONS.CRM_ACCESS,
      PERMISSIONS.LEAD_VIEW, PERMISSIONS.LEAD_MANAGE, PERMISSIONS.LEAD_FOLLOWUP,
      // Platform
      PERMISSIONS.PLATFORM_ACCESS, PERMISSIONS.PLATFORM_ADMIN,
    ],
  },

  // ── Brand admin (can view ERP, full Brand access) ──
  brand_admin: {
    code: "brand_admin",
    name: "Brand OS 管理员",
    description: "Brand OS 全部权限 + ERP 只读",
    permissions: [
      // ERP — read only
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.PRODUCT_VIEW, PERMISSIONS.SKU_VIEW,
      PERMISSIONS.WORK_VIEW, PERMISSIONS.MATERIAL_VIEW,
      PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.BOM_VIEW,
      PERMISSIONS.COST_VIEW, PERMISSIONS.PRODUCTION_VIEW,
      PERMISSIONS.ORDER_VIEW, PERMISSIONS.CUSTOMER_VIEW,
      PERMISSIONS.MEDIA_VIEW, PERMISSIONS.BANNER_VIEW,
      // Brand — full
      PERMISSIONS.BRAND_ACCESS,
      PERMISSIONS.BRAND_SERIES_VIEW, PERMISSIONS.BRAND_SERIES_EDIT,
      PERMISSIONS.BRAND_PRODUCT_VIEW, PERMISSIONS.BRAND_PRODUCT_EDIT,
      PERMISSIONS.BRAND_ARTICLE_VIEW, PERMISSIONS.BRAND_ARTICLE_CREATE, PERMISSIONS.BRAND_ARTICLE_EDIT,
      PERMISSIONS.BRAND_ARTICLE_DELETE, PERMISSIONS.BRAND_ARTICLE_PUBLISH,
      PERMISSIONS.BRAND_PAGE_VIEW, PERMISSIONS.BRAND_PAGE_EDIT,
      PERMISSIONS.BRAND_SEO_VIEW, PERMISSIONS.BRAND_SEO_EDIT,
      PERMISSIONS.BRAND_TAG_VIEW, PERMISSIONS.BRAND_TAG_EDIT,
      PERMISSIONS.BRAND_MATERIAL_VIEW, PERMISSIONS.BRAND_MATERIAL_EDIT,
      PERMISSIONS.BRAND_MEDIA_UPLOAD,
      // CRM
      PERMISSIONS.CRM_ACCESS,
      PERMISSIONS.LEAD_VIEW, PERMISSIONS.LEAD_MANAGE,
      // Platform
      PERMISSIONS.PLATFORM_ACCESS,
    ],
  },

  // ── Content editor ──
  brand_editor: {
    code: "brand_editor",
    name: "内容编辑",
    description: "品牌志完整权限 + 标签/内容/媒体查看",
    permissions: [
      // Brand
      PERMISSIONS.BRAND_ACCESS,
      PERMISSIONS.BRAND_ARTICLE_VIEW, PERMISSIONS.BRAND_ARTICLE_CREATE,
      PERMISSIONS.BRAND_ARTICLE_EDIT, PERMISSIONS.BRAND_ARTICLE_PUBLISH,
      PERMISSIONS.BRAND_PAGE_EDIT,
      PERMISSIONS.BRAND_TAG_VIEW, PERMISSIONS.BRAND_TAG_EDIT,
      PERMISSIONS.BRAND_PRODUCT_VIEW,
      PERMISSIONS.BRAND_MATERIAL_VIEW,
      PERMISSIONS.BRAND_MEDIA_UPLOAD,
      // Platform
      PERMISSIONS.PLATFORM_ACCESS,
    ],
  },

  // ── Operator ──
  brand_operator: {
    code: "brand_operator",
    name: "品牌运营",
    description: "品牌志查看 + 线索管理 + 产品查看",
    permissions: [
      // Brand
      PERMISSIONS.BRAND_ACCESS,
      PERMISSIONS.BRAND_ARTICLE_VIEW,
      PERMISSIONS.BRAND_PRODUCT_VIEW,
      // CRM
      PERMISSIONS.CRM_ACCESS,
      PERMISSIONS.LEAD_VIEW, PERMISSIONS.LEAD_MANAGE, PERMISSIONS.LEAD_FOLLOWUP,
      // Platform
      PERMISSIONS.PLATFORM_ACCESS,
    ],
  },

  // ── ERP admin (manufacturing focus) ──
  erp_admin: {
    code: "erp_admin",
    name: "ERP 管理员",
    description: "ERP 全部权限，不含 Brand 编辑",
    permissions: [
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.PRODUCT_VIEW, PERMISSIONS.PRODUCT_EDIT, PERMISSIONS.PRODUCT_DELETE,
      PERMISSIONS.SKU_VIEW, PERMISSIONS.SKU_EDIT, PERMISSIONS.SKU_DELETE,
      PERMISSIONS.WORK_VIEW, PERMISSIONS.WORK_EDIT, PERMISSIONS.WORK_DELETE,
      PERMISSIONS.MATERIAL_VIEW, PERMISSIONS.MATERIAL_EDIT, PERMISSIONS.MATERIAL_DELETE,
      PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_EDIT,
      PERMISSIONS.BOM_VIEW, PERMISSIONS.BOM_EDIT,
      PERMISSIONS.COST_VIEW, PERMISSIONS.COST_EDIT, PERMISSIONS.PROFIT_VIEW,
      PERMISSIONS.PRODUCTION_VIEW, PERMISSIONS.PRODUCTION_CREATE, PERMISSIONS.PRODUCTION_EDIT,
      PERMISSIONS.ORDER_VIEW, PERMISSIONS.ORDER_EDIT,
      PERMISSIONS.CUSTOMER_VIEW, PERMISSIONS.CUSTOMER_EDIT,
      PERMISSIONS.USER_VIEW, PERMISSIONS.USER_EDIT,
      PERMISSIONS.SETTING_VIEW, PERMISSIONS.SETTING_EDIT,
      PERMISSIONS.IMPORT_DATA, PERMISSIONS.EXPORT_DATA,
      PERMISSIONS.MEDIA_VIEW, PERMISSIONS.MEDIA_UPLOAD, PERMISSIONS.MEDIA_DELETE, PERMISSIONS.MEDIA_EDIT,
      PERMISSIONS.BANNER_VIEW, PERMISSIONS.BANNER_MANAGE,
      // Brand — read only
      PERMISSIONS.BRAND_ACCESS,
      PERMISSIONS.BRAND_SERIES_VIEW, PERMISSIONS.BRAND_PRODUCT_VIEW,
      PERMISSIONS.BRAND_ARTICLE_VIEW, PERMISSIONS.BRAND_MATERIAL_VIEW,
      // Platform
      PERMISSIONS.PLATFORM_ACCESS,
    ],
  },

  // ── Viewer (read-only) ──
  viewer: {
    code: "viewer",
    name: "访客",
    description: "仅只读 — 看板 + 产品 + 品牌志",
    permissions: [
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.PRODUCT_VIEW, PERMISSIONS.SKU_VIEW,
      PERMISSIONS.WORK_VIEW, PERMISSIONS.MATERIAL_VIEW,
      PERMISSIONS.BRAND_ARTICLE_VIEW,
      PERMISSIONS.PLATFORM_ACCESS,
    ],
  },
};

// ═══════════════════════════════════════════
// Role → Template Mapping
// ═══════════════════════════════════════════

export const ROLE_TEMPLATE_MAP: Record<string, string> = {
  SUPER_ADMIN: "platform_admin",
  ADMIN: "brand_admin",
  EDITOR: "brand_editor",
  OPERATOR: "brand_operator",
  ERP_ADMIN: "erp_admin",
  VIEWER: "viewer",
};

/** Get the template for a given role */
export function getTemplateForRole(role: string): PermissionTemplate | undefined {
  const templateCode = ROLE_TEMPLATE_MAP[role];
  return templateCode ? TEMPLATES[templateCode] : undefined;
}

/** Get all template codes */
export function getAllTemplateCodes(): string[] {
  return Object.keys(TEMPLATES);
}
